version: "3.8"

services:
  bot:
    image: vinstp/yuki-anekbot:latest

    restart: always

    build:
      context: ./bot
      dockerfile: Dockerfile

    environment:
      TG_API_ID: 'xxx'
      TG_API_HASH: 'xxx'
      TG_BOT_TOKEN: 'xxx'


  db:
    image: vinstp/yuki-anekbot-database:latest

    restart: always

    ports:
      - "5401:5432"

    volumes:
      - /home/stepan-vinokurov/Data/yuki_anekbot_init_db:/docker-entrypoint-initdb.d
      - /home/stepan-vinokurov/Data/yuki_anekbot_postgres:/var/lib/postgresql/data

    build:
      context: postgres/
      dockerfile: Dockerfile
